artifact_uri: file:C:\Users\Moham\PycharmProjects\Credit_Scoring\mlruns_V_F/348820161156891976/fb7409036d3f478db68d5d5c44ac1ba4/artifacts
end_time: 1765667571320
entry_point_name: ''
experiment_id: '348820161156891976'
lifecycle_stage: active
run_id: fb7409036d3f478db68d5d5c44ac1ba4
run_name: lgbm_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1765667557483
status: 3
tags: []
user_id: Moham
