channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.3
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.0.0
  - lz4==4.3.2
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==7.1.3
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
