artifact_uri: file:C:\Users\Moham\PycharmProjects\Credit_Scoring\mlruns_V_F/348820161156891976/b7cd7ee463eb4d379a072bde5e29cddd/artifacts
end_time: 1765667536319
entry_point_name: ''
experiment_id: '348820161156891976'
lifecycle_stage: active
run_id: b7cd7ee463eb4d379a072bde5e29cddd
run_name: logreg_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1765667488739
status: 3
tags: []
user_id: Moham
