artifact_uri: file:C:\Users\Moham\PycharmProjects\Credit_Scoring\mlruns_V_F/348820161156891976/ae7f2bba399342dd8c7f738bc60e9492/artifacts
end_time: 1765668096959
entry_point_name: ''
experiment_id: '348820161156891976'
lifecycle_stage: active
run_id: ae7f2bba399342dd8c7f738bc60e9492
run_name: lgbm_cost_curve
source_name: ''
source_type: 4
source_version: ''
start_time: 1765668096914
status: 3
tags: []
user_id: Moham
