artifact_location: file:C:\Users\Moham\PycharmProjects\Credit_Scoring\mlruns_V_F/0
creation_time: 1765667374173
experiment_id: '0'
last_update_time: 1765667374173
lifecycle_stage: active
name: Default
