creation_timestamp: 1765668164766
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1765668164766
model_id: m-f3cd265920fd45328b8105c02a0873b6
name: credit_scoring_model
run_id: fa4c68bb3ef649ebaa5b0c2e62bbd35a
run_link: null
source: models:/m-f3cd265920fd45328b8105c02a0873b6
status: READY
status_message: null
storage_location: file:C:\Users\Moham\PycharmProjects\Credit_Scoring\mlruns_V_F/348820161156891976/models/m-f3cd265920fd45328b8105c02a0873b6/artifacts
user_id: null
version: 2
