artifact_uri: file:C:\Users\Moham\PycharmProjects\Credit_Scoring\mlruns_V_F/348820161156891976/e7a5ca4e3a9d452689f1031eefabd149/artifacts
end_time: 1765667588211
entry_point_name: ''
experiment_id: '348820161156891976'
lifecycle_stage: active
run_id: e7a5ca4e3a9d452689f1031eefabd149
run_name: lgbm_cost_curve
source_name: ''
source_type: 4
source_version: ''
start_time: 1765667588170
status: 3
tags: []
user_id: Moham
